[project]
name = "update-tf-modules"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Doug Lazenby", email = "douglas.lazenby@ons.gov.uk" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
]

[project.scripts]
update-tf-modules = "update_tf_modules.cli:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-mock>=3.15.1",
    "ruff>=0.16.2",
]
